import asyncio
import random
from collections import defaultdict

from sqlalchemy import select

from auth import hash_password
from database import async_session
from models import Review, Skill, User


async def seed():
    async with async_session() as session:
        existing = await session.scalar(select(User).limit(1))
        if existing:
            print("Database already seeded, skipping.")
            return

    async with async_session() as session:
        print("Creating users...")
        users = [
            User(
                email="admin@skillhub.com",
                name="Admin",
                password_hash=hash_password("password123"),
                bio="Platform administrator and AI enthusiast. Managing SkillHub to connect developers with powerful agent tools.",
                avatar_url="https://ui-avatars.com/api/?name=Admin&background=10b981&color=fff&size=128",
                role="admin",
            ),
            User(
                email="john@dev.com",
                name="John Developer",
                password_hash=hash_password("password123"),
                bio="Full-stack developer passionate about building AI-powered tools. 5+ years experience with Python and TypeScript.",
                avatar_url="https://ui-avatars.com/api/?name=John+Developer&background=3b82f6&color=fff&size=128",
                role="user",
            ),
            User(
                email="jane@dev.com",
                name="Jane Engineer",
                password_hash=hash_password("password123"),
                bio="Senior software engineer specializing in cloud infrastructure and automation. Open source contributor.",
                avatar_url="https://ui-avatars.com/api/?name=Jane+Engineer&background=8b5cf6&color=fff&size=128",
                role="user",
            ),
            User(
                email="alex@datalab.io",
                name="Alex Chen",
                password_hash=hash_password("password123"),
                bio="Data engineer and ML ops specialist. Building bridges between data pipelines and AI agents.",
                avatar_url="https://ui-avatars.com/api/?name=Alex+Chen&background=f59e0b&color=fff&size=128",
                role="user",
            ),
            User(
                email="sarah@agentworks.dev",
                name="Sarah Miller",
                password_hash=hash_password("password123"),
                bio="AI agent architect and prompt engineer. Focused on multi-agent systems and autonomous workflows.",
                avatar_url="https://ui-avatars.com/api/?name=Sarah+Miller&background=ef4444&color=fff&size=128",
                role="user",
            ),
        ]
        session.add_all(users)
        await session.flush()
        admin, john, jane, alex, sarah = users

        print("Creating skills...")
        skills_data = [
            # --- Admin skills ---
            {"name": "Playwright Browser", "description": "Automate browser interactions with Playwright. Supports Chrome, Firefox, and WebKit for end-to-end testing, web scraping, and UI automation workflows.", "category": "browser", "framework": "custom", "install_command": "npx @skillhub/playwright", "prompt": "You are a browser automation agent. Use the Playwright Browser skill to navigate to {{url}}, interact with page elements, fill forms, click buttons, and extract data. Always wait for selectors before interacting. Return structured results as JSON with keys: status, data, screenshots_taken.", "repository_url": "https://github.com/skillhub/playwright", "documentation_url": "https://docs.skillhub.dev/playwright", "version": "2.1.0", "installs": 12500, "tags": ["browser", "automation", "testing", "scraping"], "author_id": admin.id},
            {"name": "PostgreSQL Query", "description": "Execute SQL queries against PostgreSQL databases. Supports parameterized queries, connection pooling, and transaction management for reliable data operations.", "category": "database", "framework": "langchain", "install_command": "npx @skillhub/postgres", "prompt": "You are a database agent. Use the PostgreSQL Query skill to execute SQL against the connected database. Always use parameterized queries to prevent injection. For read operations use SELECT with LIMIT. For writes, wrap in transactions. Return results as {rows: [...], affected: N, duration_ms: N}.", "repository_url": "https://github.com/skillhub/postgres", "documentation_url": "https://docs.skillhub.dev/postgres", "version": "1.5.0", "installs": 9800, "tags": ["database", "sql", "postgres"], "author_id": admin.id},
            {"name": "REST API Client", "description": "Make HTTP requests to any REST API with built-in retry logic, authentication handling, and response parsing. Supports OAuth2, API keys, and bearer tokens.", "category": "api", "framework": "custom", "install_command": "npx @skillhub/rest-client", "prompt": "You are an API integration agent. Use the REST API Client skill to make HTTP requests. Specify method (GET/POST/PUT/DELETE), URL, headers, and body. Handle pagination by following next_page links. Retry on 429/5xx with exponential backoff. Always validate response status before processing body.", "repository_url": "https://github.com/skillhub/rest-client", "documentation_url": "https://docs.skillhub.dev/rest-client", "version": "3.0.0", "installs": 15000, "tags": ["api", "http", "rest", "client"], "author_id": admin.id},
            {"name": "Chrome DevTools", "description": "Interface with Chrome DevTools Protocol for advanced browser debugging, performance profiling, and network analysis in automated workflows.", "category": "devtools", "framework": "custom", "install_command": "npx @skillhub/chrome-devtools", "prompt": "You are a browser debugging agent. Use Chrome DevTools to capture network requests, measure performance metrics (LCP, FID, CLS), take heap snapshots, and analyze JavaScript execution. Return findings as {performance: {...}, network: [...], issues: [...]}.", "repository_url": "https://github.com/skillhub/chrome-devtools", "documentation_url": "https://docs.skillhub.dev/chrome-devtools", "version": "1.2.0", "installs": 3200, "tags": ["devtools", "chrome", "debugging"], "author_id": admin.id},
            {"name": "OpenAI Assistant", "description": "Integrate OpenAI GPT models into your agent workflows. Supports function calling, streaming responses, and multi-turn conversations with context management.", "category": "ai", "framework": "openai", "install_command": "npx @skillhub/openai-assistant", "prompt": "You are an AI orchestration agent. Use the OpenAI Assistant skill to delegate tasks to GPT models. Specify the model (gpt-4o, gpt-4o-mini), system prompt, and tools available. Use streaming for long responses. Manage conversation history by passing previous messages. Max tokens should match task complexity.", "repository_url": "https://github.com/skillhub/openai-assistant", "documentation_url": "https://docs.skillhub.dev/openai-assistant", "version": "2.0.0", "installs": 14200, "tags": ["ai", "openai", "gpt", "llm"], "author_id": admin.id},
            {"name": "AWS S3 Manager", "description": "Upload, download, and manage files in AWS S3 buckets. Supports presigned URLs, multipart uploads, and bucket lifecycle management.", "category": "cloud", "framework": "custom", "install_command": "npx @skillhub/aws-s3", "prompt": "You are a cloud storage agent. Use AWS S3 Manager to upload files (use multipart for >100MB), generate presigned URLs (default 1hr expiry), list objects with prefix filtering, and manage bucket policies. Always specify content-type on upload. Return {key, url, size_bytes, etag} for uploads.", "repository_url": "https://github.com/skillhub/aws-s3", "documentation_url": "https://docs.skillhub.dev/aws-s3", "version": "1.8.0", "installs": 8700, "tags": ["cloud", "aws", "s3", "storage"], "author_id": admin.id},
            {"name": "Slack Messenger", "description": "Send messages, create channels, and manage Slack workspaces programmatically. Supports rich message formatting, file uploads, and interactive components.", "category": "messaging", "framework": "custom", "install_command": "npx @skillhub/slack", "prompt": "You are a team communication agent. Use Slack Messenger to send messages to channels or DMs. Use Block Kit for rich formatting. For notifications, include context blocks with metadata. For alerts, use red color attachments. Always confirm channel exists before posting. Thread replies using thread_ts.", "repository_url": "https://github.com/skillhub/slack", "documentation_url": "https://docs.skillhub.dev/slack", "version": "1.3.0", "installs": 6100, "tags": ["messaging", "slack", "notifications"], "author_id": admin.id},
            {"name": "CSV Processor", "description": "Parse, transform, and generate CSV files with support for large datasets. Includes streaming mode for memory-efficient processing of files with millions of rows.", "category": "file", "framework": "langchain", "install_command": "npx @skillhub/csv-processor", "prompt": "You are a data processing agent. Use CSV Processor to read, transform, and write CSV files. For large files (>50MB), use streaming mode. Specify column mappings, filters, and aggregations. Supported operations: filter_rows, map_columns, group_by, sort, deduplicate. Output format: {rows_processed, rows_output, columns}.", "repository_url": "https://github.com/skillhub/csv-processor", "documentation_url": "https://docs.skillhub.dev/csv-processor", "version": "1.0.0", "installs": 4300, "tags": ["file", "csv", "data", "etl"], "author_id": admin.id},
            {"name": "Google Analytics", "description": "Fetch analytics data from Google Analytics 4 properties. Supports custom reports, real-time data, and audience segmentation for data-driven insights.", "category": "analytics", "framework": "custom", "install_command": "npx @skillhub/google-analytics", "prompt": "You are an analytics reporting agent. Use Google Analytics to pull metrics (sessions, users, pageviews, conversions) for date ranges. Specify dimensions (page, source, country) and metrics. Use realtime endpoint for live data. Format results as tables with totals row. Always include comparison to previous period.", "repository_url": "https://github.com/skillhub/google-analytics", "documentation_url": "https://docs.skillhub.dev/google-analytics", "version": "1.1.0", "installs": 5400, "tags": ["analytics", "google", "reporting"], "author_id": admin.id},

            # --- John skills ---
            {"name": "Anthropic Claude", "description": "Leverage Anthropic Claude models for natural language tasks. Features tool use, vision capabilities, and structured output generation with XML parsing.", "category": "ai", "framework": "anthropic", "install_command": "npx @skillhub/anthropic-claude", "prompt": "You are an AI delegation agent. Use Anthropic Claude for complex reasoning, analysis, and content generation. Choose model by task: claude-sonnet-4-20250514 for most tasks, opus for deep analysis. Use system prompts to set behavior. For structured output, ask Claude to respond in XML tags. Pass images as base64 for vision tasks.", "repository_url": "https://github.com/skillhub/anthropic-claude", "documentation_url": "https://docs.skillhub.dev/anthropic-claude", "version": "1.4.0", "installs": 11300, "tags": ["ai", "anthropic", "claude", "llm"], "author_id": john.id},
            {"name": "Selenium Grid", "description": "Distribute browser automation across multiple nodes with Selenium Grid. Supports parallel test execution and cross-browser compatibility testing at scale.", "category": "browser", "framework": "custom", "install_command": "npx @skillhub/selenium-grid", "prompt": "You are a distributed testing agent. Use Selenium Grid to run browser tests in parallel across nodes. Specify browser (chrome, firefox, edge), version, and platform. Distribute test suites by splitting into chunks. Collect results from all nodes and merge. Report {passed, failed, skipped, duration_ms}.", "repository_url": "https://github.com/skillhub/selenium-grid", "documentation_url": "https://docs.skillhub.dev/selenium-grid", "version": "1.0.0", "installs": 4800, "tags": ["browser", "selenium", "testing", "parallel"], "author_id": john.id},
            {"name": "GraphQL Client", "description": "Execute GraphQL queries and mutations against any endpoint. Supports subscriptions, batching, and automatic persisted queries for optimized performance.", "category": "api", "framework": "custom", "install_command": "npx @skillhub/graphql-client", "prompt": "You are a GraphQL integration agent. Use GraphQL Client to execute queries and mutations. Always request only needed fields to minimize payload. Use variables for dynamic values, never string interpolation. For paginated data, use cursor-based pagination with pageInfo { hasNextPage, endCursor }. Handle errors from the errors array.", "repository_url": "https://github.com/skillhub/graphql-client", "documentation_url": "https://docs.skillhub.dev/graphql-client", "version": "1.2.0", "installs": 6700, "tags": ["api", "graphql", "client"], "author_id": john.id},
            {"name": "LangChain Agent", "description": "Build sophisticated AI agents using LangChain framework. Includes memory management, tool orchestration, and chain-of-thought reasoning capabilities.", "category": "ai", "framework": "langchain", "install_command": "npx @skillhub/langchain-agent", "prompt": "You are a meta-agent builder. Use LangChain Agent to create task-specific sub-agents with tools, memory, and reasoning chains. Define agent type (react, plan-and-execute, openai-functions). Assign tools from the skill registry. Set memory type (buffer, summary, vector). Monitor token usage and set max_iterations to prevent runaway chains.", "repository_url": "https://github.com/skillhub/langchain-agent", "documentation_url": "https://docs.skillhub.dev/langchain-agent", "version": "0.9.1", "installs": 9200, "tags": ["ai", "langchain", "agent", "orchestration"], "author_id": john.id},
            {"name": "Discord Bot", "description": "Create and manage Discord bots with full API coverage. Supports slash commands, message components, voice channels, and webhook integrations.", "category": "messaging", "framework": "custom", "install_command": "npx @skillhub/discord-bot", "prompt": "You are a Discord automation agent. Use Discord Bot to send messages, manage channels, and respond to commands. Use embeds for rich content (set color, title, fields, thumbnail). For interactive flows, use buttons and select menus with custom_id. Rate limit: 50 requests/second per route. Always handle interaction responses within 3 seconds.", "repository_url": "https://github.com/skillhub/discord-bot", "documentation_url": "https://docs.skillhub.dev/discord-bot", "version": "1.6.0", "installs": 5500, "tags": ["messaging", "discord", "bot"], "author_id": john.id},
            {"name": "Azure Blob Storage", "description": "Manage files in Azure Blob Storage containers. Supports block blobs, append blobs, and page blobs with automatic tier management and CDN integration.", "category": "cloud", "framework": "custom", "install_command": "npx @skillhub/azure-blob", "prompt": "You are an Azure storage agent. Use Azure Blob Storage to upload, download, and manage blobs in containers. Set blob tier (Hot/Cool/Archive) based on access patterns. Use SAS tokens for temporary access (default 24hr). For large uploads, use block blob with 4MB chunks. Return {blob_name, url, size, content_type, tier}.", "repository_url": "https://github.com/skillhub/azure-blob", "documentation_url": "https://docs.skillhub.dev/azure-blob", "version": "1.1.0", "installs": 3800, "tags": ["cloud", "azure", "storage", "blob"], "author_id": john.id},
            {"name": "PDF Generator", "description": "Generate PDF documents from HTML templates or structured data. Supports custom fonts, images, tables, and page layouts with automatic pagination.", "category": "file", "framework": "custom", "install_command": "npx @skillhub/pdf-generator", "prompt": "You are a document generation agent. Use PDF Generator to create PDFs from HTML templates or structured data. Pass template name and variables for dynamic content. Set page size (A4, Letter), margins, and orientation. For tables, pass data as arrays. Include header/footer with page numbers. Return {file_path, pages, size_bytes}.", "repository_url": "https://github.com/skillhub/pdf-generator", "documentation_url": "https://docs.skillhub.dev/pdf-generator", "version": "2.3.0", "installs": 7100, "tags": ["file", "pdf", "document", "generation"], "author_id": john.id},
            {"name": "Webpack Analyzer", "description": "Analyze webpack bundle sizes and dependencies. Provides tree-shaking suggestions, duplicate module detection, and build performance optimization tips.", "category": "devtools", "framework": "custom", "install_command": "npx @skillhub/webpack-analyzer", "prompt": "You are a build optimization agent. Use Webpack Analyzer to inspect bundle composition. Analyze entry points, chunk sizes, and dependency trees. Flag duplicates (same module in multiple chunks), oversized chunks (>250KB gzipped), and unused exports. Suggest code splitting points. Return {total_size, chunks: [...], duplicates: [...], recommendations: [...]}.", "repository_url": "https://github.com/skillhub/webpack-analyzer", "documentation_url": "https://docs.skillhub.dev/webpack-analyzer", "version": "1.0.0", "installs": 2100, "tags": ["devtools", "webpack", "performance"], "author_id": john.id},
            {"name": "MySQL Connector", "description": "Execute queries against MySQL and MariaDB databases. Supports prepared statements, connection pooling, and replication-aware routing for read/write splitting.", "category": "database", "framework": "custom", "install_command": "npx @skillhub/mysql", "prompt": "You are a MySQL database agent. Use MySQL Connector for CRUD operations with prepared statements. Route reads to replicas, writes to primary. Use connection pooling (max 10 connections). For bulk inserts, use batch mode with 1000-row chunks. Always set query timeout (default 30s). Return {rows, affected, warnings, duration_ms}.", "repository_url": "https://github.com/skillhub/mysql", "documentation_url": "https://docs.skillhub.dev/mysql", "version": "1.3.0", "installs": 5900, "tags": ["database", "mysql", "sql"], "author_id": john.id},

            # --- Jane skills ---
            {"name": "CrewAI Orchestrator", "description": "Build multi-agent systems with CrewAI. Define agent roles, goals, and backstories to create collaborative AI teams that solve complex tasks autonomously.", "category": "ai", "framework": "crewai", "install_command": "npx @skillhub/crewai-orchestrator", "prompt": "You are a multi-agent coordinator. Use CrewAI Orchestrator to assemble agent crews for complex tasks. Define each agent with: role, goal, backstory, and allowed_tools. Create tasks with descriptions, expected_output, and agent assignments. Set process type (sequential or hierarchical). Monitor crew execution and collect final output from each task.", "repository_url": "https://github.com/skillhub/crewai-orchestrator", "documentation_url": "https://docs.skillhub.dev/crewai-orchestrator", "version": "1.0.0", "installs": 8400, "tags": ["ai", "crewai", "multi-agent", "orchestration"], "author_id": jane.id},
            {"name": "AutoGen Studio", "description": "Create conversational AI agents with Microsoft AutoGen. Supports group chat, code execution, and human-in-the-loop workflows for complex reasoning tasks.", "category": "ai", "framework": "autogen", "install_command": "npx @skillhub/autogen-studio", "prompt": "You are an AutoGen workflow builder. Create conversational agent teams with defined roles. Configure UserProxy for human-in-the-loop, AssistantAgent for AI tasks. Enable code execution in Docker sandboxes. Set max_consecutive_auto_reply to prevent infinite loops. For group chats, define speaker selection (round_robin or auto). Collect chat history as output.", "repository_url": "https://github.com/skillhub/autogen-studio", "documentation_url": "https://docs.skillhub.dev/autogen-studio", "version": "0.9.0", "installs": 6300, "tags": ["ai", "autogen", "conversational", "agent"], "author_id": jane.id},
            {"name": "Puppeteer Scraper", "description": "High-performance web scraping with Puppeteer. Handles SPAs, infinite scroll, and dynamic content with automatic wait strategies and anti-detection measures.", "category": "browser", "framework": "custom", "install_command": "npx @skillhub/puppeteer-scraper", "prompt": "You are a web scraping agent. Use Puppeteer Scraper to extract data from websites. Set viewport, user agent, and cookies before navigating. Wait for content with waitForSelector or networkidle. Use page.evaluate() to extract data via DOM queries. For paginated sites, loop through pages. Respect robots.txt and add delays between requests (1-3s). Return structured JSON.", "repository_url": "https://github.com/skillhub/puppeteer-scraper", "documentation_url": "https://docs.skillhub.dev/puppeteer-scraper", "version": "1.7.0", "installs": 10100, "tags": ["browser", "puppeteer", "scraping", "automation"], "author_id": jane.id},
            {"name": "GCP Cloud Functions", "description": "Deploy and manage Google Cloud Functions. Supports HTTP triggers, Pub/Sub events, and Cloud Storage triggers with automatic scaling and monitoring.", "category": "cloud", "framework": "custom", "install_command": "npx @skillhub/gcp-functions", "prompt": "You are a serverless deployment agent. Use GCP Cloud Functions to deploy, invoke, and manage functions. Specify runtime (nodejs20, python312), trigger type (http, pubsub, storage), memory (256MB default), and timeout (60s default). Deploy from source directory or inline code. Monitor with {invocations, errors, latency_p99}.", "repository_url": "https://github.com/skillhub/gcp-functions", "documentation_url": "https://docs.skillhub.dev/gcp-functions", "version": "1.2.0", "installs": 4500, "tags": ["cloud", "gcp", "serverless", "functions"], "author_id": jane.id},
            {"name": "Email Sender", "description": "Send transactional and marketing emails via SMTP or API providers like SendGrid and Mailgun. Supports templates, attachments, and delivery tracking.", "category": "messaging", "framework": "custom", "install_command": "npx @skillhub/email-sender", "prompt": "You are an email automation agent. Use Email Sender to deliver transactional emails. Specify provider (sendgrid, mailgun, smtp), from/to addresses, subject, and html body. Use templates with {{variable}} substitution. Attach files as base64 with filename and content_type. Track delivery via {message_id, status, delivered_at}. Respect rate limits.", "repository_url": "https://github.com/skillhub/email-sender", "documentation_url": "https://docs.skillhub.dev/email-sender", "version": "2.1.0", "installs": 7800, "tags": ["messaging", "email", "smtp", "notifications"], "author_id": jane.id},
            {"name": "JSON Transformer", "description": "Transform, validate, and manipulate JSON data with JSONPath expressions and JMESPath queries. Supports schema validation, diff generation, and merge operations.", "category": "file", "framework": "langchain", "install_command": "npx @skillhub/json-transformer", "prompt": "You are a data transformation agent. Use JSON Transformer to reshape, validate, and merge JSON. Use JSONPath ($.store.book[*].author) to extract fields. Use JMESPath for complex queries. Validate against JSON Schema before processing. Operations: extract, flatten, merge, diff, validate. Return {input_size, output_size, transformations_applied, validation_errors}.", "repository_url": "https://github.com/skillhub/json-transformer", "documentation_url": "https://docs.skillhub.dev/json-transformer", "version": "1.4.0", "installs": 5200, "tags": ["file", "json", "transform", "validation"], "author_id": jane.id},
            {"name": "Docker Manager", "description": "Manage Docker containers, images, and networks programmatically. Supports compose deployments, health checks, and log streaming for containerized applications.", "category": "devtools", "framework": "custom", "install_command": "npx @skillhub/docker-manager", "prompt": "You are a container orchestration agent. Use Docker Manager to run, stop, and inspect containers. For deployments, use compose files with service definitions. Monitor health via healthcheck endpoints. Stream logs with --follow and --tail 100. Prune unused images/volumes to free space. Return {container_id, status, ports, health, uptime}.", "repository_url": "https://github.com/skillhub/docker-manager", "documentation_url": "https://docs.skillhub.dev/docker-manager", "version": "1.5.0", "installs": 8900, "tags": ["devtools", "docker", "containers", "deployment"], "author_id": jane.id},
            {"name": "Stripe Payments", "description": "Process payments and manage subscriptions with Stripe. Supports checkout sessions, invoices, refunds, and webhook handling for complete payment workflows.", "category": "api", "framework": "custom", "install_command": "npx @skillhub/stripe-payments", "prompt": "You are a payments integration agent. Use Stripe Payments to create checkout sessions, manage subscriptions, and process refunds. Always use idempotency keys for mutations. Create products and prices before checkout sessions. For subscriptions, set billing_cycle_anchor and proration_behavior. Handle webhooks for async events. Return {payment_id, status, amount, currency}.", "repository_url": "https://github.com/skillhub/stripe-payments", "documentation_url": "https://docs.skillhub.dev/stripe-payments", "version": "3.0.0", "installs": 11800, "tags": ["api", "stripe", "payments", "billing"], "author_id": jane.id},
            {"name": "Redis Cache", "description": "Interact with Redis for caching, pub/sub messaging, and data structures. Supports clusters, sentinel, and streams for high-performance data operations.", "category": "database", "framework": "custom", "install_command": "npx @skillhub/redis-cache", "prompt": "You are a caching and messaging agent. Use Redis Cache for key-value storage with TTL, pub/sub channels, and sorted sets. Set expiry on all cache keys (default 1hr). Use hash types for structured objects. For rate limiting, use INCR with EXPIRE. For queues, use LPUSH/BRPOP. Monitor with {keys_count, memory_used, hit_rate, connected_clients}.", "repository_url": "https://github.com/skillhub/redis-cache", "documentation_url": "https://docs.skillhub.dev/redis-cache", "version": "1.6.0", "installs": 9500, "tags": ["database", "redis", "cache", "pubsub"], "author_id": jane.id},

            # --- Alex skills ---
            {"name": "Snowflake Warehouse", "description": "Query and manage Snowflake data warehouses. Supports multi-cluster compute, time travel queries, and zero-copy cloning for analytics workflows.", "category": "database", "framework": "custom", "install_command": "npx @skillhub/snowflake", "prompt": "You are a data warehouse agent. Use Snowflake Warehouse to run analytical queries on large datasets. Set warehouse size (X-SMALL to 4X-LARGE) based on query complexity. Use RESULT_SCAN for async queries. Leverage time travel (AT/BEFORE) for historical data. Clone tables for safe experimentation. Return {query_id, rows, warehouse, credits_used, duration_ms}.", "repository_url": "https://github.com/skillhub/snowflake", "documentation_url": "https://docs.skillhub.dev/snowflake", "version": "1.3.0", "installs": 6800, "tags": ["database", "snowflake", "analytics", "warehouse"], "author_id": alex.id},
            {"name": "Apache Kafka Producer", "description": "Publish messages to Apache Kafka topics with exactly-once semantics. Supports schema registry, message compression, and partitioning strategies.", "category": "messaging", "framework": "custom", "install_command": "npx @skillhub/kafka-producer", "prompt": "You are a streaming data agent. Use Kafka Producer to publish events to topics. Set key for partition routing, value as JSON payload. Use schema registry for Avro/Protobuf serialization. Configure acks=all for durability, compression=lz4 for throughput. Batch messages (linger.ms=5) for efficiency. Return {topic, partition, offset, timestamp}.", "repository_url": "https://github.com/skillhub/kafka-producer", "documentation_url": "https://docs.skillhub.dev/kafka-producer", "version": "2.0.0", "installs": 5100, "tags": ["messaging", "kafka", "streaming", "events"], "author_id": alex.id},
            {"name": "dbt Runner", "description": "Execute dbt models, tests, and snapshots for data transformation pipelines. Supports incremental builds, model selection, and freshness checks.", "category": "devtools", "framework": "custom", "install_command": "npx @skillhub/dbt-runner", "prompt": "You are a data transformation pipeline agent. Use dbt Runner to build models, run tests, and check source freshness. Select models with --select (tag:daily, path:marts). Use --full-refresh for schema changes, incremental by default. Run tests after builds. Check freshness before transforms. Return {models_built, tests_passed, tests_failed, freshness_warnings}.", "repository_url": "https://github.com/skillhub/dbt-runner", "documentation_url": "https://docs.skillhub.dev/dbt-runner", "version": "1.7.0", "installs": 7200, "tags": ["devtools", "dbt", "data", "transformation"], "author_id": alex.id},
            {"name": "Airflow DAG Trigger", "description": "Trigger and monitor Apache Airflow DAGs remotely. Supports parameterized runs, task-level status tracking, and SLA monitoring.", "category": "devtools", "framework": "custom", "install_command": "npx @skillhub/airflow-trigger", "prompt": "You are a workflow orchestration agent. Use Airflow DAG Trigger to start DAG runs with configuration parameters. Monitor execution via task instance states (success, running, failed). Wait for completion with polling (30s intervals). Check SLA misses. For failed tasks, fetch logs and suggest fixes. Return {dag_id, run_id, state, duration, task_states: {...}}.", "repository_url": "https://github.com/skillhub/airflow-trigger", "documentation_url": "https://docs.skillhub.dev/airflow-trigger", "version": "1.2.0", "installs": 4400, "tags": ["devtools", "airflow", "orchestration", "pipeline"], "author_id": alex.id},
            {"name": "BigQuery Analyst", "description": "Run analytical queries on Google BigQuery with cost controls. Supports scheduled queries, materialized views, and ML model training with BQML.", "category": "database", "framework": "custom", "install_command": "npx @skillhub/bigquery", "prompt": "You are a BigQuery analytics agent. Run SQL queries with cost estimation first (dry_run=true). Use partitioned tables and cluster keys for efficiency. Set maximum_bytes_billed to prevent runaway costs. For ML, use CREATE MODEL with training data. Export results to GCS for large outputs. Return {job_id, rows, bytes_processed, cost_estimate, cache_hit}.", "repository_url": "https://github.com/skillhub/bigquery", "documentation_url": "https://docs.skillhub.dev/bigquery", "version": "2.1.0", "installs": 8300, "tags": ["database", "bigquery", "analytics", "ml"], "author_id": alex.id},
            {"name": "Pandas DataFrame", "description": "Perform in-memory data analysis with Pandas. Supports groupby, pivot tables, time series resampling, and merge/join operations on structured data.", "category": "file", "framework": "langchain", "install_command": "npx @skillhub/pandas-df", "prompt": "You are a data analysis agent. Use Pandas DataFrame for in-memory data manipulation. Load from CSV, JSON, Parquet, or SQL. Chain operations: filter → groupby → agg → sort. Use .describe() for quick stats. For time series, set DatetimeIndex and use .resample(). Memory limit: 2GB — for larger data, use chunked reading. Return {shape, columns, dtypes, summary_stats}.", "repository_url": "https://github.com/skillhub/pandas-df", "documentation_url": "https://docs.skillhub.dev/pandas-df", "version": "1.5.0", "installs": 9100, "tags": ["file", "pandas", "data", "analysis"], "author_id": alex.id},
            {"name": "Terraform Deployer", "description": "Plan and apply Terraform infrastructure changes. Supports state management, module composition, and drift detection for IaC workflows.", "category": "cloud", "framework": "custom", "install_command": "npx @skillhub/terraform", "prompt": "You are an infrastructure-as-code agent. Use Terraform Deployer to plan, apply, and destroy infrastructure. Always run plan before apply. Review resource changes (add/change/destroy) before confirming. Use workspaces for environment isolation. Lock state during operations. Return {plan_summary: {add, change, destroy}, resources_managed, drift_detected, outputs: {...}}.", "repository_url": "https://github.com/skillhub/terraform", "documentation_url": "https://docs.skillhub.dev/terraform", "version": "2.0.0", "installs": 10500, "tags": ["cloud", "terraform", "iac", "infrastructure"], "author_id": alex.id},
            {"name": "Datadog Monitor", "description": "Create and manage Datadog monitors, dashboards, and alerts. Supports metric queries, log analysis, and APM trace correlation.", "category": "analytics", "framework": "custom", "install_command": "npx @skillhub/datadog", "prompt": "You are an observability agent. Use Datadog Monitor to query metrics (avg, sum, max over time windows), create monitors with thresholds, and investigate incidents. Correlate APM traces with logs using trace_id. Set monitor alerts with escalation policies. For dashboards, use timeseries and toplist widgets. Return {monitors: [...], alerts_active, metrics_queried}.", "repository_url": "https://github.com/skillhub/datadog", "documentation_url": "https://docs.skillhub.dev/datadog", "version": "1.4.0", "installs": 6600, "tags": ["analytics", "datadog", "monitoring", "observability"], "author_id": alex.id},

            # --- Sarah skills ---
            {"name": "Multi-Agent Router", "description": "Intelligent routing layer for multi-agent systems. Classifies incoming tasks and delegates to specialized agents based on capability matching and load balancing.", "category": "ai", "framework": "langchain", "install_command": "npx @skillhub/agent-router", "prompt": "You are a task routing meta-agent. Use Multi-Agent Router to classify incoming requests and delegate to the best-fit specialist agent. Define agent capabilities as {name, skills, max_concurrent, priority}. Route by: keyword matching → semantic similarity → fallback. Track agent load and queue tasks when at capacity. Return {routed_to, confidence, queue_position, estimated_wait}.", "repository_url": "https://github.com/skillhub/agent-router", "documentation_url": "https://docs.skillhub.dev/agent-router", "version": "1.0.0", "installs": 7800, "tags": ["ai", "routing", "multi-agent", "orchestration"], "author_id": sarah.id},
            {"name": "Prompt Chain Builder", "description": "Design and execute multi-step prompt chains with branching logic. Supports conditional flows, variable passing, and chain-of-thought decomposition.", "category": "ai", "framework": "langchain", "install_command": "npx @skillhub/prompt-chain", "prompt": "You are a prompt engineering agent. Use Prompt Chain Builder to create multi-step LLM workflows. Define steps with {prompt_template, model, output_key}. Chain outputs as inputs to next steps via {{previous_step.output_key}}. Add conditional branches with if/else on outputs. Set retry logic per step. Validate intermediate outputs with assertions. Return {steps_executed, final_output, tokens_used, chain_duration_ms}.", "repository_url": "https://github.com/skillhub/prompt-chain", "documentation_url": "https://docs.skillhub.dev/prompt-chain", "version": "2.1.0", "installs": 8900, "tags": ["ai", "prompts", "chains", "workflow"], "author_id": sarah.id},
            {"name": "Vector Store Manager", "description": "Manage vector embeddings in Pinecone, Weaviate, or ChromaDB. Supports upsert, semantic search, metadata filtering, and namespace isolation.", "category": "database", "framework": "langchain", "install_command": "npx @skillhub/vector-store", "prompt": "You are a vector search agent. Use Vector Store Manager to store and query embeddings. Choose provider (pinecone, weaviate, chroma). Upsert vectors with {id, values, metadata}. Query with top_k (default 10), score_threshold (0.7), and metadata filters. Use namespaces to isolate datasets. For RAG, combine with LLM skill. Return {matches: [{id, score, metadata}], query_time_ms}.", "repository_url": "https://github.com/skillhub/vector-store", "documentation_url": "https://docs.skillhub.dev/vector-store", "version": "1.3.0", "installs": 11200, "tags": ["database", "vectors", "embeddings", "search"], "author_id": sarah.id},
            {"name": "RAG Pipeline", "description": "Retrieval-Augmented Generation pipeline combining document retrieval with LLM synthesis. Supports chunking strategies, reranking, and citation tracking.", "category": "ai", "framework": "langchain", "install_command": "npx @skillhub/rag-pipeline", "prompt": "You are a knowledge retrieval agent. Use RAG Pipeline to answer questions from document collections. Configure: chunk_size (512 tokens), overlap (50), embedding_model (text-embedding-3-small), retriever_k (5), reranker (cohere). Pass query, get retrieved chunks with sources. Synthesize answer with citations [1][2]. Track {chunks_retrieved, chunks_used, sources, confidence_score}.", "repository_url": "https://github.com/skillhub/rag-pipeline", "documentation_url": "https://docs.skillhub.dev/rag-pipeline", "version": "1.8.0", "installs": 13400, "tags": ["ai", "rag", "retrieval", "generation"], "author_id": sarah.id},
            {"name": "Webhook Server", "description": "Create temporary webhook endpoints to receive and process HTTP callbacks. Supports payload validation, retry handling, and event filtering.", "category": "api", "framework": "custom", "install_command": "npx @skillhub/webhook-server", "prompt": "You are a webhook handler agent. Use Webhook Server to create ephemeral endpoints that receive callbacks. Specify expected payload schema for validation. Filter events by type field. Queue received events for processing. Set timeout (5min default) and max_events. Verify webhook signatures when secret is provided. Return {endpoint_url, events_received: [...], validation_errors}.", "repository_url": "https://github.com/skillhub/webhook-server", "documentation_url": "https://docs.skillhub.dev/webhook-server", "version": "1.1.0", "installs": 4200, "tags": ["api", "webhook", "callback", "events"], "author_id": sarah.id},
            {"name": "GitHub Actions Runner", "description": "Trigger and monitor GitHub Actions workflows. Supports workflow dispatch, artifact download, and matrix build status aggregation.", "category": "devtools", "framework": "custom", "install_command": "npx @skillhub/github-actions", "prompt": "You are a CI/CD automation agent. Use GitHub Actions Runner to dispatch workflows with inputs, monitor run status, and download artifacts. Specify repo (owner/name), workflow file, and ref (branch/tag). Poll run status every 30s. On failure, fetch job logs for the failed step. Download artifacts by name. Return {run_id, status, conclusion, duration, artifacts: [...], failed_step}.", "repository_url": "https://github.com/skillhub/github-actions", "documentation_url": "https://docs.skillhub.dev/github-actions", "version": "1.5.0", "installs": 7500, "tags": ["devtools", "github", "ci-cd", "automation"], "author_id": sarah.id},
            {"name": "Twilio SMS", "description": "Send and receive SMS messages via Twilio. Supports two-way conversations, message scheduling, and delivery status tracking.", "category": "messaging", "framework": "custom", "install_command": "npx @skillhub/twilio-sms", "prompt": "You are a messaging agent. Use Twilio SMS to send text messages to phone numbers. Format numbers as E.164 (+1234567890). Keep messages under 160 chars for single segment. For scheduled messages, use send_at with ISO timestamp (min 15min ahead). Track delivery via {sid, status, direction, segments, price}. For conversations, store message history by phone number.", "repository_url": "https://github.com/skillhub/twilio-sms", "documentation_url": "https://docs.skillhub.dev/twilio-sms", "version": "1.2.0", "installs": 5800, "tags": ["messaging", "twilio", "sms", "notifications"], "author_id": sarah.id},
            {"name": "Prometheus Query", "description": "Query Prometheus metrics for infrastructure and application monitoring. Supports PromQL, range queries, and alert rule evaluation.", "category": "analytics", "framework": "custom", "install_command": "npx @skillhub/prometheus", "prompt": "You are a metrics analysis agent. Use Prometheus Query to fetch time-series metrics with PromQL. Use rate() for counters, avg_over_time() for gauges. Set step interval based on range (1m for <1h, 5m for <24h, 1h for >24h). For alerting, evaluate threshold expressions. Compare current vs baseline (1w ago). Return {metric, values: [{timestamp, value}], labels, step, query_time_ms}.", "repository_url": "https://github.com/skillhub/prometheus", "documentation_url": "https://docs.skillhub.dev/prometheus", "version": "1.0.0", "installs": 5300, "tags": ["analytics", "prometheus", "metrics", "monitoring"], "author_id": sarah.id},
        ]

        skills = []
        for data in skills_data:
            skill = Skill(**data)
            skills.append(skill)
            session.add(skill)
        await session.flush()

        print("Creating reviews...")
        random.seed(42)

        review_comments_positive = [
            "Great tool for automating workflows! Highly recommended.",
            "Excellent documentation and easy to integrate.",
            "Works perfectly out of the box. Saved me hours of work.",
            "Solid performance and great error handling.",
            "One of the best skills on the marketplace.",
            "Very reliable. Using it in production without any issues.",
            "Clean API design and great TypeScript support.",
            "Fast, efficient, and well-maintained.",
            "Love the streaming support. Works great for large datasets.",
            "The best tool in its category. Period.",
            "Prompt template is incredibly well-crafted. Makes the agent so much more effective.",
            "Setup took 5 minutes and it just works. Excellent DX.",
            "The error messages are actually helpful. Rare for a tool like this.",
            "Been using this daily for 3 months. Rock solid.",
        ]
        review_comments_neutral = [
            "Decent tool but could use better documentation.",
            "Works well for basic use cases. Advanced features need polish.",
            "Good tool overall. Some edge cases could be handled better.",
            "Does what it says. Nothing more, nothing less.",
            "Functional but the API could be more intuitive.",
            "Solid foundation but missing some features I expected.",
            "Prompt template works but could be more detailed for complex scenarios.",
        ]
        review_comments_negative = [
            "Setup was confusing. Needs a better getting started guide.",
            "Had issues with error handling in edge cases.",
            "Performance could be better for large-scale operations.",
            "Lacks some features compared to alternatives.",
            "The prompt template doesn't cover enough edge cases.",
        ]

        all_reviewers = [admin, john, jane, alex, sarah]
        reviews_created = []
        seen_pairs = set()

        for skill in skills:
            num_reviews = random.randint(2, 4)
            eligible_reviewers = [u for u in all_reviewers if u.id != skill.author_id]
            reviewers = random.sample(eligible_reviewers, min(num_reviews, len(eligible_reviewers)))

            for reviewer in reviewers:
                pair = (reviewer.id, skill.id)
                if pair in seen_pairs:
                    continue
                seen_pairs.add(pair)

                rating = random.choices([1, 2, 3, 4, 5], weights=[2, 5, 12, 35, 46])[0]
                if rating >= 4:
                    comment = random.choice(review_comments_positive)
                elif rating == 3:
                    comment = random.choice(review_comments_neutral)
                else:
                    comment = random.choice(review_comments_negative)

                review = Review(
                    rating=rating,
                    comment=comment,
                    skill_id=skill.id,
                    user_id=reviewer.id,
                )
                session.add(review)
                reviews_created.append((skill.id, rating))

        await session.flush()

        skill_ratings = defaultdict(list)
        for skill_id, rating in reviews_created:
            skill_ratings[skill_id].append(rating)

        for skill in skills:
            ratings = skill_ratings.get(skill.id, [])
            skill.review_count = len(ratings)
            skill.avg_rating = round(sum(ratings) / len(ratings), 2) if ratings else 0

        await session.commit()
        print(f"Created {len(users)} users, {len(skills)} skills, {len(reviews_created)} reviews.")
        print("Seed complete!")


if __name__ == "__main__":
    asyncio.run(seed())
